# Generated by Django 4.1.7 on 2023-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_men_unisex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctotal', models.CharField(max_length=225)),
                ('shp', models.CharField(max_length=225)),
                ('tot', models.CharField(max_length=225)),
            ],
        ),
    ]
