# Generated by Django 4.1.7 on 2023-06-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cimage',
            field=models.CharField(default='default_image.jpg', max_length=225),
        ),
        migrations.AddField(
            model_name='cart',
            name='cname',
            field=models.CharField(default='default_cname', max_length=225),
        ),
        migrations.AddField(
            model_name='cart',
            name='cprice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cart',
            name='cstock',
            field=models.IntegerField(default=0),
        ),
    ]
