# Generated by Django 4.1.7 on 2023-09-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='men',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unisex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='women',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
